### ISSUE TITLE
[BUG] Javascript Error Uncaught Exception Invalid local header on mod folder check

### ISSUE THREAD

**Issue by jmaggart1979** [jtsage/FS_Mod_Checker#49]
**Describe the bug**
When scanning a mod folder with 116 mods the scan starts and then the error pops up. The scan will not complete at this point.

**To Reproduce**
1. Go to FS Mod Folder Checker
2. Click on Load Folder
3. Click on mod folder where I keep several mods
4. Click on Scan mods and save games
6. See error

**Expected behavior**
Complete scan successfully and list details as usual in categories

**Screenshots**
![2022-05-29 20_07_14-Farming Simulator Mod Folder Checker](https://user-images.githubusercontent.com/106501385/170906091-cfde09f6-5404-43db-8d5b-be457b8091cb.jpg)
![image](https://user-images.githubusercontent.com/106501385/170906153-e3df8ead-6838-493e-93df-b8173ddbed6a.png)
![image](https://user-images.githubusercontent.com/106501385/170906553-8be621c8-4b35-4cdb-b757-8e13498b4fe8.png)
![image](https://user-images.githubusercontent.com/106501385/170906601-953c6c9a-049a-40f0-9784-3b83d8375a1b.png)
![image](https://user-images.githubusercontent.com/106501385/170906660-cea9027e-8f61-48d4-856f-db1752271fdb.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
Windows 10 Home

**Additional context**
I have run the scan on other folders successfully but it just seems to error out on this folder. I also included screenshots of the mod folder that is causing the issue.

**Comment by jtsage** [comment]
Hmm.  my guess is it is one single mod that is throwing the issue.  But, you are right that the checker is supposed to recover gracefully from that.  Any chance you can split it into two halves (and again, etc) to try and narrow down the bad file?  If you do happen to figure out which one is doing it, and it's not something that you absolutely can't send, I'd love to take a look at the offender and see what check I am missing.

**Comment by jmaggart1979** [comment]
I will do that and let you know.

**Comment by jmaggart1979** [comment]
Found the culprit...

https://jclsfarmequipment.itch.io/international-60-flail-shredder
