### ISSUE TITLE
FS22 Mod Folder Checker

### ISSUE THREAD

**Issue by bradleypowel** [jtsage/FS_Mod_Checker#50]
When you go to the conflicts and go to remove the mod it says FS19 Mod Checker : Cannnot move to quarantine.

**Comment by jtsage** [comment]
At the very bottom of the window is a link that says "view debug log" - this will give a bit more information on what went wrong.  Without seeing that, at a guess - the quarantine location is either unset or un-writable.  You can change it in settings.  (The little gear icon)
