### ISSUE TITLE
FSModChecker-Portable-3.1.0 incorrectly defines "Used" compared to FSModAssistant-Portable-1.1.1. [BUG]

### ISSUE THREAD

**Issue by vitalii2011** [jtsage/FS_Mod_Checker#54]
**Describe the bug**
In the title. I have no saves that would not have this greenhouse built on the map. 

**Screenshots**
![Image 002](https://user-images.githubusercontent.com/41552153/201628136-d0906760-c4b6-411a-8c28-33285fa0ff32.png)
![Image 001](https://user-images.githubusercontent.com/41552153/201628174-8ed9df1e-4ffa-4727-9984-84b539e95aa2.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10]

**Comment by jtsage** [comment]
Any chance you can shoot me a zip of the save you used - I suspect one of the two of them is right, and I'm not sure which. 

Thanks!

**Comment by vitalii2011** [comment]
Which file sharing service to drop the .zip on?

**Comment by jtsage** [comment]
doesn't matter to me, if it's small enough jtsage+fs@gmail.com is fine.

**Comment by jtsage** [comment]
Thanks.  From line 1504 in placables:

`<placeable modName="AK_sixtimes_Greenhouses" filename="$moddir$AK_sixtimes_Greenhouses/greenhouseLarge.xml" id="115" position="798.42895507813 120.96698760986 -770.056640625" rotation="0 327.04147859315 0" age="11.000000" price="60000.000000" farmId="1">` 

So `Used` is correct.  I guess I have to stop being lazy and do some updating of the folder checker.  Thanks for pointing this out
