### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by BattleHook** [jtsage/FS_Mod_Checker#55]
It takes a lot of manual work and time to clean-up modfolders (yes, I have multiple mod-folders, for different types of gameplay or savegames).
Your tool is already a great improvement in managing mods 👍, however it lacks the final touch of being able to perform actions from the tool.

-I would like mods that are not used (e.g. for Savegame7) to be moved to a dedicated folder (e.g. mod_unused_SG7). This should IMHO be user-initiated, not automatic after scan.
-I would like mods that I select to be moved to a folder I choose
-would like to be able to scan multiple mod-folders and see if there are conflicts in versions and then the possibility to exchange the old for the new versions.

Also it would be very nice if you could add the choice for a dark-theme ( the white screen is now hurting my eyes 😉 ).
And maybe choice of character-type? Bold would be nice too. 

Anyway, I hope this request is picked-up, since it has been a while since the last release of this tool, so I don't no if you still actively support this tool.....

Don't see this as criticism, I really like the tool as it is now 😄, but I think there are some improvements possible.

**Comment by jtsage** [comment]
It's not so much abandoned as improved in a different direction.  Nearly all of the functionality you mentioned is present in some way here : https://github.com/FSGModding/FSG_Mod_Assistant - along with a bunch of new features, like folder switching which is a huge, huge improvement over the massive single folder like this tool expected.

**Comment by BattleHook** [comment]
Thank you for your response. I'll certainly will take a look at the FGS Mod Assistant. Maybe an idea to put this information on top of description of this GitHub project?
